apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: devguard-operator
  name: devguard-operator
  namespace: devguard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: devguard-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devguard-operator
    spec:
      containers:
      - image: ghcr.io/l3montree-dev/devguard-operator:latest
        name: operator
        env:
          - name: DEVGUARD_TOKEN
            valueFrom:
              secretKeyRef:
                name: "devguard-operator"
                key: "devguard-token"
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: DEVGUARD_API_URL
            value: "https://api.devguard.org"
          - name: DEVGUARD_PROJECT_NAME
            value: "devguard-operator"
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        securityContext:
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 101
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
          - mountPath: /work
            name: work
          - mountPath: /tmp
            name: tmp
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          timeoutSeconds: 3
          httpGet:
            path: "/health"
            port: 8081
        readinessProbe:
          timeoutSeconds: 3
          httpGet:
            path: "/health"
            port: 8081
      volumes:
        - name: work
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      securityContext:
        fsGroup: 101
      serviceAccountName: devguard-operator
